udpated

diff --git a/Jenkinsfile.CI-UAT-deployment b/Jenkinsfile.CI-UAT-deployment
--- a/Jenkinsfile.CI-UAT-deployment
+++ b/Jenkinsfile.CI-UAT-deployment
@@ -72,7 +72,7 @@ pipeline {
         }
 
         stage('SonarQube analysis') {
-    steps {
+          steps {
         withSonarQubeEnv('sonar-scanner-admin') {
             sh '''
                 SONAR_TOKEN=$(aws secretsmanager get-secret-value \
@@ -80,6 +80,14 @@ pipeline {
                   --region ap-south-1 \
                   --query 'SecretString' \
                   --output text | jq -r '.sonar_token')
+
+                if [ -z "$SONAR_TOKEN" ] || [ "$SONAR_TOKEN" = "null" ]; then
+                    echo "ERROR: SONAR_TOKEN is empty"
+                    exit 1
+                fi
+
+                echo "Sonar token fetched successfully"
+                echo "Token length: ${#SONAR_TOKEN}"
 
                 ${SCANNER_HOME}/bin/sonar-scanner \
                   -Dsonar.projectKey=Helm \
